### ISSUE TITLE
Tracking Issue V1

### ISSUE THREAD

**Issue by affrae** [affrae/ghas-report-downloader#3]
- [x] Error Checking and Handling
- [x] User Input Data checking and sanitization
- [x] Better details in the list reports function to help choose which report
- [x] Download the report(s) using the `-g` option (listing report analysis IDs)
- [x] Download the report(s) for the most recent commit to a Pull Request source branch using the `-p` option (listing Pull Request numbers )
- [x] Download the report(s) for a given Commit SHA or list of Commit SHAs
- [x] Enable an option to provide a directory to download the reports to
- [x] Better docs

**Comment by affrae** [comment]
Closing as v1 feature complete
