### ISSUE TITLE
Tracking Issue V2

### ISSUE THREAD

**Issue by affrae** [affrae/ghas-report-downloader#4]
- [ ] Verbose `-v` and `-V` levels sorted out (right now it is a little noisy)
- [ ] Implement a unit testing framework
- [ ] Support for GitHub Enterprise Server
